### PR TITLE
Remove incorrect test

### PR DESCRIPTION
**Pull request by davidanthoff**
This is the reason the tests don't pass and that one test seems simply wrong.

### CODE REVIEW

**Comment by pfitzseb** [comment]
Also remove the `import: rest` from the top of the file and maybe remove that particular example from the readme?

**Comment by MikeInnes** [comment]
I think we may have changed this to `tail`, so that would be a better fix.

**Comment by davidanthoff** [comment]
Done.

**Comment by pfitzseb** [comment]
bump @MikeInnes

**Comment by ranjanan** [comment]
This fixes #48

**Comment by MikeInnes** [comment]
Thanks!

**Pull request merged**
