### PR TITLE
Bump Lazy from 0.3 to 0.4

### PR DESCRIPTION
**Pull request by ranjanan**
Use Julia 0.4 instead of 0.3. MacroTools (a dependency in the REQUIRE file) uses only v0.4 and above.

### CODE REVIEW

**Comment by MikeInnes** [comment]
Great, thanks for looking at this!

**Comment by ranjanan** [comment]
Sure! :)

**Comment by tkelman** [comment]
travis needs updating for this

**Comment by tkelman** [comment]
only the latest tags of macrotools are 0.4-only. there are early tags that claim to support 0.3, which is what this package would use on 0.3

**Pull request merged**
